version: "3.3"
services:
  csvserver:
    image: "infracloudio/csvserver:latest"
    ports:
      - "9393:9300"
    volumes:
      - ./inputdata:/csvserver/inputdata
    environment:
      CSVSERVER_BORDER: orange
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml


